openapi: 3.0.1
info:
  title: API Rest ms-prueba-bch
  description: API Rest ms-prueba-bch
  version: 1.0.0
servers:
  - url: "http://localhost:8080/ms-prueba-bch"
tags:
  - name: Api ms-prueba-bch
    description: Rest ms-prueba-bch
paths:
  /v1/indicadores/tipo/todos:
    get:
      tags:
        - todos
      summary: Get para todos los indicadores financieros
      operationId: todos
      parameters:
        - name: response
          in: path
          required: true
          schema:
            type: HttpServletResponse
        - name: request
          in: path
          required: true
          schema:
            type: HttpServletRequest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: RetornoJson
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /v1/indicadores/tipo/uf:
    get:
      tags:
        - uf
      summary: Get para indicador UF
      operationId: uf
      parameters:
        - name: response
          in: path
          required: true
          schema:
            type: HttpServletResponse
        - name: request
          in: path
          required: true
          schema:
            type: HttpServletRequest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: RetornoJson
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /v1/indicadores/tipo/uf/{fecha}:
    post:
      tags:
        - uffecha
      summary: Get para indicador UF según fecha dd-mm-yyyy
      operationId: fecha
      parameters:
        - name: fecha
          in: path
          required: true
          schema:
            type: string      
        - name: response
          in: path
          required: true
          schema:
            type: HttpServletResponse            
        - name: request
          in: path
          required: true
          schema:
            type: HttpServletRequest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: RetornoJson
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /v1/indicadores/tipo/uf/{año}:
    post:
      tags:
        - ufaño
      summary: Get para indicador UF según año
      operationId: año
      parameters:
        - name: año
          in: path
          required: true
          schema:
            type: string        
        - name: response
          in: path
          required: true
          schema:
            type: HttpServletResponse      
        - name: request
          in: path
          required: true
          schema:
            type: HttpServletRequest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: RetornoJson
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
components:
  responses:
    Unauthorized:
      description: (Unauthorized) No Autorizado
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorGenerico"
    NotFound:
      description: (NotFound) No se encontro informacion
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorGenerico"
    BadRequest:
      description: (Bad Request) Los datos enviados son incorrectos o hay datos
        obligatorios no enviados
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorGenerico"
    ServerError:
      description: Error en servidor
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorGenerico"
  schemas:
    ResponseGenerico:
      title: ResponseGenerico
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ErrorGenerico:
      title: ErrorGenerico
      type: object
      properties:
        code:
          type: string
        message:
          type: string